name: helpi_admin
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  file_selector: ^1.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.4
  dio: ^5.7.0
  signalr_netcore: ^1.4.4
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.6.1
  excel: ^4.0.6
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
